HELLOWORLD_VERSION = 1.0-1
export HELLOWORLD_VERSION
HELLOWORLD = helloworld_$(HELLOWORLD_VERSION)_$(CONFIGURED_ARCH).deb
$(HELLOWORLD)_SRC_PATH = $(SRC_PATH)/helloworld

#SONIC_MAKE_DEBS
SONIC_DPKG_DEBS += $(HELLOWORLD)

HELLOWORLD_DBG = helloworld-dbgsym_$(HELLOWORLD_VERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(HELLOWORLD),$(HELLOWORLD_DBG)))